<a href="https://colab.research.google.com/github/Wikanda-Hongboonmee/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np # package สำหรับทำงานกับข้อมูลที่เป็นตัวเลข ที่อยู่ในรูป matrix

#**Numpy Array**

### สร้าง Numpy Array (Matrix)

In [3]:
np_a = np.array([[1,2,3],[4,5,6]]) # สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [4]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np_a.shape

(2, 3)

In [6]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

matrix transpose

In [8]:
np_a.T  # กลับแถวเป็นหลัก หลักเป็นแถว

array([[1, 4],
       [2, 5],
       [3, 6]])

### สร้าง matrix เริ่มต้น (zeros, ones)

In [10]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
np_200 = 200*np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

### สร้าง matrix random

In [13]:
np.random.randn(5,5) # random เลขมาจาก normal distribution ที่มี mu = 0 std = 1

array([[ 2.33785002,  0.68422161,  0.13799745, -0.10563662,  0.42943532],
       [-0.06774043, -0.54710752, -0.48575408, -0.06396437,  0.4494887 ],
       [-0.34711251, -0.05011241,  1.22798491, -1.62020772, -0.67730366],
       [ 0.29237929, -0.91560059,  0.6477699 , -1.34126522,  0.6931197 ],
       [-0.67090623, -0.55167091, -0.34396587,  1.76480481,  0.58505623]])

In [16]:
2+(5*np.random.randn(3,3)) # random เลขมาจาก normal distribution ที่มี mu = 2 std = 5

array([[-2.96240741,  9.62245445,  6.13899443],
       [ 6.75359135, -5.86056553,  2.79458984],
       [ 9.15111623, -2.46476632,  3.19756695]])

In [18]:
np.random.randint(5,11,(4,5)) # random เลขจำนวนเต็มระหว่าง 5 ถึง 11 [5,11) ขนาด (4x5)

array([[ 5, 10,  9,  8,  7],
       [ 6, 10, 10,  9,  7],
       [ 8,  7,  8,  7,  5],
       [ 6,  7,  6,  6,  7]])